In [1]:
# IMPORT LIB
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns

In [2]:
# create a datset
from sklearn.datasets import make_classification

In [6]:
X, y = make_classification(n_samples= 1000, n_features=10,n_classes=2 ,random_state=42)

In [13]:
#train test split
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [14]:
x_train

array([[ 2.16351564e-01, -1.44385482e+00,  8.63296483e-02, ...,
        -1.22071243e+00, -5.81760524e-01, -5.50536849e-01],
       [ 1.23113339e+00,  6.18886298e-01,  3.61459838e-01, ...,
         3.11652856e-01, -3.73454077e+00,  3.81309612e-01],
       [ 4.30245208e-01,  1.04043089e+00,  5.27722816e-01, ...,
         2.13808794e-01,  6.39390501e-03, -3.68939439e-01],
       ...,
       [ 4.09146664e-02,  4.27962627e-01, -2.35298234e-03, ...,
        -1.92277177e+00, -1.71047718e-01,  1.63925652e+00],
       [ 3.39379203e-01, -6.40154457e-01,  2.52539950e-01, ...,
        -1.39922826e+00, -5.29912480e-01, -7.34810898e-01],
       [ 1.84815207e+00, -3.13058031e-01,  1.78069642e+00, ...,
         6.04515326e-01, -1.56102804e+00, -1.25040773e+00]])

In [15]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,

In [16]:
x_test

array([[ 0.74030596,  0.42548993,  0.6039124 , ..., -0.709441  ,
        -0.98264957, -1.3716737 ],
       [-1.49577819,  0.38135283, -1.2763343 , ...,  0.57404193,
         1.80201193, -0.63014283],
       [-0.14407863, -0.00928856,  0.02366179, ..., -0.34287886,
         0.65257238,  1.8134077 ],
       ...,
       [-1.67945551,  0.47314545, -1.40250885, ...,  0.46643129,
         2.12312866, -0.23780704],
       [-0.50417344, -0.36861937, -0.45662085, ...,  0.28305316,
         0.52109091,  1.11968778],
       [ 0.30714244,  0.74661136,  0.45012969, ..., -0.85222464,
         0.24438526,  2.27582543]])

In [17]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [18]:
# model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [19]:
logistic.fit(x_train, y_train)

LogisticRegression()

In [21]:
y_pred = logistic.predict(x_test)

In [ ]:
# performance metrics 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score()