In [1]:
# IMPORT LIB
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns

In [2]:
# create a datset
from sklearn.datasets import make_classification

In [3]:
X, y = make_classification(n_samples= 1000, n_features=10,n_classes=2 ,random_state=42)

In [4]:
#train test split
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [5]:
x_train

array([[ 2.16351564e-01, -1.44385482e+00,  8.63296483e-02, ...,
        -1.22071243e+00, -5.81760524e-01, -5.50536849e-01],
       [ 1.23113339e+00,  6.18886298e-01,  3.61459838e-01, ...,
         3.11652856e-01, -3.73454077e+00,  3.81309612e-01],
       [ 4.30245208e-01,  1.04043089e+00,  5.27722816e-01, ...,
         2.13808794e-01,  6.39390501e-03, -3.68939439e-01],
       ...,
       [ 4.09146664e-02,  4.27962627e-01, -2.35298234e-03, ...,
        -1.92277177e+00, -1.71047718e-01,  1.63925652e+00],
       [ 3.39379203e-01, -6.40154457e-01,  2.52539950e-01, ...,
        -1.39922826e+00, -5.29912480e-01, -7.34810898e-01],
       [ 1.84815207e+00, -3.13058031e-01,  1.78069642e+00, ...,
         6.04515326e-01, -1.56102804e+00, -1.25040773e+00]])

In [6]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,

In [7]:
x_test

array([[ 0.74030596,  0.42548993,  0.6039124 , ..., -0.709441  ,
        -0.98264957, -1.3716737 ],
       [-1.49577819,  0.38135283, -1.2763343 , ...,  0.57404193,
         1.80201193, -0.63014283],
       [-0.14407863, -0.00928856,  0.02366179, ..., -0.34287886,
         0.65257238,  1.8134077 ],
       ...,
       [-1.67945551,  0.47314545, -1.40250885, ...,  0.46643129,
         2.12312866, -0.23780704],
       [-0.50417344, -0.36861937, -0.45662085, ...,  0.28305316,
         0.52109091,  1.11968778],
       [ 0.30714244,  0.74661136,  0.45012969, ..., -0.85222464,
         0.24438526,  2.27582543]])

In [8]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [9]:
# model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [10]:
logistic.fit(x_train, y_train)

LogisticRegression()

In [11]:
y_pred = logistic.predict(x_test)

In [12]:
# performance metrics 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_pred, y_test)
confusion = confusion_matrix(y_pred, y_test)
classification = classification_report(y_pred, y_test)

In [13]:
print(accuracy)
print(confusion)
print(classification)

0.8454545454545455
[[132  31]
 [ 20 147]]
              precision    recall  f1-score   support

           0       0.87      0.81      0.84       163
           1       0.83      0.88      0.85       167

    accuracy                           0.85       330
   macro avg       0.85      0.85      0.85       330
weighted avg       0.85      0.85      0.85       330



## Hyperparameter training

In [15]:
model = LogisticRegression()
penalty= ['l1', 'l2', 'elasticnet']
c_values =[100, 50, 10, 1.0, 0.1, 0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [16]:
params =dict(penalty= penalty, C=c_values, solver =solver)

In [18]:
from sklearn.model_selection import StratifiedKFold

cv=StratifiedKFold()

In [20]:
# Gridsearch CV
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator= model, param_grid=params, scoring= 'accuracy', cv=cv, n_jobs=-1)


In [21]:
grid.fit(x_train, y_train)

E:\code\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
300 fits failed out of a total of 540.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "E:\code\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\code\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\code\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 50, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [22]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [23]:
Y_PRED = grid.predict(x_test)

In [24]:
# performance metrics 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(Y_PRED, y_test)
confusion = confusion_matrix(Y_PRED, y_test)
classification = classification_report(Y_PRED, y_test)

In [25]:
print(accuracy)
print(confusion)
print(classification)

0.8545454545454545
[[139  35]
 [ 13 143]]
              precision    recall  f1-score   support

           0       0.91      0.80      0.85       174
           1       0.80      0.92      0.86       156

    accuracy                           0.85       330
   macro avg       0.86      0.86      0.85       330
weighted avg       0.86      0.85      0.85       330




### Randomied Search cv


In [26]:
from sklearn.model_selection import RandomizedSearchCV

In [27]:
randomcv = RandomizedSearchCV(estimator=model, param_distributions=params, cv= 5, scoring='accuracy')

In [28]:
randomcv.fit(x_train, y_train)

E:\code\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
40 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "E:\code\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\code\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\code\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 50, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [29]:
randomcv.best_score_

0.864179104477612

In [30]:
randomcv.best_estimator_

LogisticRegression(C=100, solver='newton-cg')

## Logistic regression for multiclass

In [31]:
x, Y= make_classification(n_samples=1000,n_features=10 ,n_informative=3 ,n_classes=3, random_state=12)

In [32]:
x

array([[ 0.98605799,  1.60265235, -0.88603382, ...,  0.93483483,
        -0.23939986, -1.73490482],
       [ 0.42036859,  3.70877379, -0.52055331, ...,  1.82033051,
         1.6427496 , -0.16960427],
       [-0.62738366,  3.2164944 ,  0.0170093 , ...,  2.98480248,
         2.10391968,  1.62944024],
       ...,
       [-0.12266822, -3.61835789,  1.18885351, ..., -2.31236771,
        -1.69659196, -2.03679392],
       [ 2.1663785 ,  1.36871429,  0.28573021, ...,  0.79897282,
         1.73767899,  0.93623643],
       [-0.14837336, -2.07627798,  0.90553922, ..., -0.73882255,
        -1.57500036,  0.98340852]])

In [33]:
Y

array([1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2,
       0, 2, 0, 2, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0,
       2, 1, 0, 2, 1, 1, 2, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 1, 0,
       0, 1, 0, 2, 0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 0,
       0, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 0, 2, 2, 2, 1, 0, 0, 1,
       2, 1, 1, 2, 2, 2, 2, 0, 1, 1, 1, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 2,
       2, 0, 2, 2, 1, 1, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2,
       2, 0, 1, 2, 1, 1, 0, 2, 2, 0, 2, 1, 0, 0, 2, 0, 2, 1, 1, 2, 0, 0,
       2, 2, 2, 1, 0, 1, 0, 1, 2, 2, 1, 2, 0, 2, 0, 1, 2, 0, 2, 2, 1, 1,
       0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 1, 0, 1,
       1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 2, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0,
       1, 2, 2, 1, 1, 1, 1, 0, 2, 0, 2, 0, 1, 1, 2, 1, 2, 1, 1, 0, 0, 1,
       2, 0, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 2, 2, 0,

In [34]:
# Train test split
x_train, x_test, y_train, y_test = train_test_split(x, Y, test_size=0.30, random_state= 42)


In [35]:
x_train

array([[-7.48319027e-02,  1.21923574e+00, -9.96768019e-02, ...,
         1.98080704e-03,  1.42517483e+00, -3.05041590e-03],
       [-1.90105543e-01,  7.82384377e-01,  2.50954348e-01, ...,
         3.12555475e+00, -2.00265815e+00, -1.65178504e+00],
       [ 9.68373148e-01, -2.02315808e+00,  4.88970002e-01, ...,
        -7.21371692e-01, -1.42987973e+00,  1.14059035e+00],
       ...,
       [ 2.61608194e-01, -1.21665073e+00,  1.91969406e+00, ...,
        -2.59300036e-02, -5.68185348e-01,  1.12285857e+00],
       [-2.89568256e-01,  2.68948071e+00, -3.23750984e-01, ...,
         1.13630761e+00,  9.57458979e-01, -2.31531896e+00],
       [ 9.98084351e-02, -1.78368323e-01,  5.15802971e-01, ...,
         1.26890944e+00, -8.34573955e-01,  6.13520458e-01]])

In [36]:
y_train

array([2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 1, 1,
       2, 0, 1, 0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 0, 1, 2, 0, 2, 1,
       0, 0, 1, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 2, 1, 0, 0, 1, 0, 0, 2,
       1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2,
       0, 0, 2, 1, 2, 2, 1, 0, 2, 1, 0, 0, 2, 0, 1, 2, 2, 2, 2, 2, 1, 0,
       0, 2, 2, 0, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 2, 2, 0, 1, 2, 1, 1, 0,
       0, 1, 1, 2, 2, 0, 0, 2, 1, 2, 1, 2, 2, 0, 2, 0, 1, 1, 0, 1, 2, 0,
       0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0,
       2, 0, 2, 2, 1, 0, 1, 2, 2, 2, 1, 2, 2, 0, 1, 0, 2, 1, 1, 1, 2, 0,
       2, 0, 0, 2, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 0, 2, 0, 1, 0,
       0, 0, 2, 1, 1, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 1, 2, 0,

In [40]:
logistic = LogisticRegression(multi_class='ovr')

In [41]:
logistic.fit(x_train, y_train)
y_pred = logistic.predict(x_test)


E:\code\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [42]:
y_pred

array([0, 0, 2, 0, 0, 1, 1, 2, 1, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 0, 2, 0,
       0, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 1, 0, 2, 2, 1, 0, 2, 1, 1, 0,
       1, 0, 0, 2, 1, 0, 2, 1, 0, 2, 1, 2, 0, 0, 1, 2, 0, 1, 2, 2, 0, 0,
       1, 0, 0, 1, 2, 2, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 1,
       2, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 1, 2, 1, 1,
       2, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 0,
       1, 0, 2, 1, 1, 2, 2, 0, 2, 1, 0, 0, 2, 1, 1, 2, 0, 0, 1, 0, 0, 2,
       0, 1, 2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 2,
       2, 2, 1, 2, 1, 0, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 0, 0, 2, 0, 1, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1, 2, 1, 0, 1, 0, 2, 2, 1,
       2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2,
       2, 0, 2, 2, 0, 1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 1, 2, 2,
       0, 0, 1, 0, 2, 0, 1, 2, 2, 1, 1, 2, 0, 1])

In [45]:
# performance matrics
score = accuracy(y_pred, y_test)
print(score)
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

TypeError: 'float' object is not callable